### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by jtfotso** [Tuebel/FmiWrapper#1]
Hi Tuebel,
I'm not able to run the FmiWrapper_net on my system because of the System.AccessViolationException on the Instantiate method. I thank you for help.

**Comment by Tuebel** [comment]
Hi I tried to run the provided console application and noticed that it crashed after using Reset.
This is an error that usually occurs with FMUs that have been generated with Matlab/Simulink (like the provided test_sf.fmu).
I have re-enabled the workaround to free and re-instantiate the fmu, please pull the latest commit :).
Does this fix the problem for you?

**Comment by jtfotso** [comment]
Hi Tuebel,
my problem was fixed.
Thanks for your help
