### ISSUE TITLE
fatal error GC

### ISSUE THREAD

**Issue by jtfotso** [Tuebel/FmiWrapper#3]
Hallo Tim,
ich kann mit dem FMU nur 2 maximal 3 male rechnen. ich bekomme die folgende Fehlermeldung (attached file
![fatalError](https://user-images.githubusercontent.com/10279251/61370045-c88e3d00-a891-11e9-8c7a-554a935188aa.PNG)
)

Danke für deine Rückmeldung
freundliche Grüßen

Jules

**Comment by Tuebel** [comment]
Hallo Jules,

das klingt so, als würdest du von verschiedenen Threads auf die Fmu zugreifen. Hast du das Problem auch in einer einfachen Single-Thread Anwendung?

Gruß
Tim

**Comment by jtfotso** [comment]
Hallo Tim. Ich bedanke mich für deine Rückmeldung. 
Ich war in Urlaub deswegen reagiere ich erst heute. 
Das ist mein Problem. Ich habe immer in C# programmiert und fast nie mir Sorgen über Thread gemacht. Ich kann dir nicht sagen, ob ich in einer einfachen Single-Thread oder Multiple Thread bin. Aber ich habe fast nichts geändert. Die Funktionalität hat immer funktioniert. Der einzige Unterschied ist die Anzahl von Parameter. Die funktionalität hat mit 10 Parametern problemlos funktioniert. Aber jetzt haben wir mehr als 100 Parameter. Wie weiß ich, dass ich von einen einzigen Threads auf die Fmu zugreifen ?. 
Danke für deine Rückmeldung.

Gruß
Jules

**Comment by Tuebel** [comment]
Einen zweiten Thread müsstest du explizit starten zum Beispiel mit einem `Task `oder `BackgroundWorker`. Bei welcher Codezeile tritt der Fehler genau auf, bei SetValues?
