### ISSUE TITLE
fmu.GetInteger(...) not working

### ISSUE THREAD

**Issue by jtfotso** [Tuebel/FmiWrapper#4]
Hi Tim,
I'm facing some issues with the FmiWrapper. The outputs of the function GetInteger seems to not working. I don't know if you could help me on that. I checked in Modellica and everything is ok. 
But in C# the integer output never changes..

Thanks and Regards

Jules

**Comment by Tuebel** [comment]
I can't find any apparent bug in the code. Do the other functions work as expected? Could your provide a test fmu?
