### ISSUE TITLE
fmu.DoStep doesn't work with negative numbers

### ISSUE THREAD

**Issue by bvlassa** [Tuebel/FmiWrapper#5]
i'm trying to  solve a timeserie of numbers from -1000 till 1000, but get only errors:
Instance name: simple_multiplier_Instance, status: fmi2OK, category: debug, message: simple_multiplier_fmi2SetReal, #r134217728# = 1008.000000 (input variable 0)
Instance name: simple_multiplier_Instance, status: fmi2OK, category: debug, message: simple_multiplier_fmi2SetReal called at t=  0.000000000000000000e+00 with 1 value(s)
input Real values: 1008
Instance name: simple_multiplier_Instance, status: fmi2Error, category: stepping, message: simple_multiplier_fmi2DoStep: Current communication point (1008.000000) does not match last evaluation time (0.000000) within tolerance 0.000000. Time rollback is not allowed
Instance name: simple_multiplier_Instance, status: fmi2OK, category: debug, message: simple_multiplier_fmi2GetReal, #r268435456# = 0.000000 (output variable 0)
Instance name: simple_multiplier_Instance, status: fmi2OK, category: debug, message: simple_multiplier_fmi2GetReal called at t=  0.000000000000000000e+00 with 1 value(s)

We use   fmu.SetReal(setRealVr, setRealValues); and fmu.GetReal(getRealVr, getRealValues);

Thanks in advance,

**Comment by Tuebel** [comment]
Hi bvlassa,

what values do you pass to the `do_step` function?
Are you explicitly trying to simulate timepoints which lie in the past with negative `communication_step_size`?

**Comment by bvlassa** [comment]
Thanks for the quick reaction.
I found my issue, I used the wrong timepoint, a negative timepoint is not required.
