### ISSUE TITLE
Failed to open file (null)/BouncingBall_info.json for reading => FmiFunctions.Instantiate

### ISSUE THREAD

**Issue by d0op** [Tuebel/FmiWrapper#7]
hello 

we are using modelica and exorting the testdata BouncingBall (any would do) and getting error during initation:

assert            | debug   | Failed to open file (null)/BouncingBall_info.json for reading: No such file or directory
getBestJumpBuffer got mmc_jumper=0000000000000000, globalJumpBuffer=0000000000000000

the .fmu is loaded corrctly and is valid via fmu-checker:
FMI Version
2.0
FMI Type
Model Exchange, Co-Simulation
Model Name
BouncingBall
Platforms
c-code, win64
Continuous States
2
Event Indicators
3
Model Variables
10
Generation Date
2021-12-22T10:27:37Z
Generation Tool
OpenModelica Compiler OpenModelica v1.18.0 (64-bit)

The file its crying about can be located in the fmu/resource

//regards

**Comment by Tuebel** [comment]
Hi,

I guess you extracted the whole fmu to a specific location?
Did you provide the absolute path to the extracted `resource` directory in `instantiate` for the parameter `resource_location`?

**Comment by d0op** [comment]
hello, i found some documentation and found out about the resourcepath needed as absolute path to unzipped dir. and it did work after that. :D was asking bit to fast. nice wrapper anyway. its clear and slick, hopefully we have good use of it :D
