### ISSUE TITLE
How to use ModelExchange's model

### ISSUE THREAD

**Issue by JamesBaiJun** [Tuebel/FmiWrapper#8]
Hi Tuebel,
Now, I can use Co-Simulation's Model in my C# App by your wrapper.
And I want to use ModelExchange's Model, Does this wrapper support ModelExchange's model ?

Thanks.

**Comment by Tuebel** [comment]
Hi,
it has been a while when I implemented this, but I think the ModelExchange types are available. However, you will need to provide your own solver / integrator.

**Comment by JamesBaiJun** [comment]
> 嗨，当我实现这个时已经有一段时间了，但我认为模型交换类型是可用的。但是，您需要提供自己的求解器/积分器。

Ok. I'll try that
